#!/bin/bash

# gcd
#
# change directory to ghq managed repository
#
function gcd() {
  if [[ $1 == "" ]]; then
    PECO=peco
  else
    PECO="peco --query $1"
  fi
  cd $(ghq list --full-path | eval $PECO)
}

