#!/bin/bash
# zsh history search
function phistory() {
    local tac
    exists gtac && tac="gtac" || { exists tac && tac="tac" || { tac="tail -r" } }

    # show command history
    BUFFER=$(fc -l -n 1 | eval $tac | peco --query "$LBUFFER")
    CURSOR=$#BUFFER # move cursor
    zle -R -c # refresh
}

# register shell function to widget
zle -N phistory

bindkey '^R' phistory
