---
- ag
- asciinema
- autossh
- awscli
- certbot
- colordiff
- coreutils # change mac command to like GNU Linux
- ctags
- direnv
- findutils
- fzf
- gnu-tar
- gzip
- heroku
- hugo
- htop
- iproute2mac # ip command
- jid # json inremental digger
- jq # json perser pipeline
- kubectx
- kubeval
- libidn # encode/decode utf-8 domain
- lzop
# - mobile-shell
- mycli
- openssl
- p7zip # to un7zip chronium os image
- packer
- peco # interactive filter
- percona-toolkit
- pgcli
- putty
- python
- readline # use for ruby compile
- rclone
- snzip #zip&unzip snappy format
- source-highlight
- sshrc
- terraform
- tig
- tree
- translate-shell
- watch
- wget
