---
- asciinema
- ag
- awscli
- certbot
- colordiff
- coreutils # change mac command to like GNU Linux
- cask
- ctags
- direnv
- findutils
- fzf
- go
- gnu-tar
- gzip
- heroku
- hugo
- htop
- iproute2mac # ip command
- jid # json inremental digger
- jq # json perser pipeline
- kubectx
- libidn # encode/decode utf-8 domain
- lzop
# - mobile-shell
- mycli
- mruby
- mruby-cli
- openssl
- p7zip # to un7zip chronium os image
- packer
- peco # interactive filter
- percona-toolkit
- pgcli
- putty
- python
- rbenv
- readline # use for ruby compile
- ruby-build
- rclone
- snzip
- source-highlight
- sshrc
- terraform
- tig
- tree
- translate-shell
- watch
- wget
