#!/bin/bash

#
# script for OS X
#

# #
# # change readline for use japanese
# #
# CURRENT_READLINE=`otool -L $(find /opt/boxen/rbenv -name readline.bundle) | grep /opt/boxen/homebrew/Cellar/readline`
# if [ ${#CURRENT_READLINE} > 0 ]; then
#   echo "[notice] already updated readline.bundle"
# else
#   find /opt/boxen/rbenv -name readline.bundle -exec install_name_tool -change /usr/lib/libedit.3.dylib `find /opt/boxen -name libreadline.dylib` {} \;
#   echo "update readline.bundle"
# fi

#
# fotns
#
if [ ! -d $HOME/Dropbox/dev/fonts ]; then
  echo "[error] Fonts directory is not exist"
elif [ -f $HOME/Library/Fonts/Source\ Code\ Pro\ Regular\ for\ Powerline.otf ]; then
  echo "[info] already copied fonts"
else
  echo "Copying fonts to local"
  cp $HOME/Dropbox/dev/fonts/* $HOME/Library/Fonts/
fi

#
# Add git config local to $HOME
#
if [ ! -f $HOME/Dropbox/dev/.gitconfig.local ]; then
  echo "[error] .gitconfig.local is not exist in $HOME/Dropbox/dev"
elif [ -f $HOME/.gitconfig.local ]; then
  echo "[info] already simlinked .gitconfig.local"
else
  ln -s $HOME/Dropbox/dev/.gitconfig.local $HOME/
  echo "Copying .gitconfig.local to local"
fi

#
# tmuxinator
#
if [ ! -d $HOME/Dropbox/dev/tmuxinator ]; then
  echo "[ERROR] tmuxinator setting directory is not exist"
elif [ -L $HOME/.tmuxinator ]; then
  echo "[INFO] Symlinked tmuxinator"
else
  echo "Symlink tmuxinator"
  ln -s $HOME/Dropbox/dev/tmuxinator $HOME/.tmuxinator
fi

#
# rsa keys
#
if [ -e $HOME/.ssh/id_rsa ]; then
  echo "[info] Exit id_rsa"
else
  # cd ~/.ssh/
  # ssh-keygen -t rsa
  # echo "generating rsa key"
fi

#
# KEY
#
if [ -L $HOME/.zsh.env ]; then
  echo "[info] Exit zsh.env"
else
  ln -s $HOME/Dropbox/dev/zsh.env $HOME/.zsh.env
  echo "Symlink zsh.env"
fi

# ## heroku setting
# #
# # add to pubkey
# #
# HOST_PC_NAME=`cat ${HOME}/.ssh/id_rsa.pub | awk -F' ' '{ print $3 }'`
# RSA_IN_HEROKU=`heroku keys | grep ${HOST_PC_NAME}`
# if [ ${#RSA_IN_HEROKU} > 0 ]; then
#   echo "[notice] already added this host rsa key to heroku"
# else
#   heroku keys:add
#   echo "adding rsa key to heroku"
# fi

