#!/bin/bash

#
# symlink dot files and directories
#
DOT_FILES=(vimrc tmux.conf zshrc zshenv gitconfig gitignore_global gitattributes tigrc gemrc ptignore)
DOT_DIRECTORIES=(vim bundle git_template)

for file in ${DOT_FILES[@]}
do
  if [ -e $HOME/.$file ]; then
    echo "[WARN] $file file is existed."
  else
    ln -s $HOME/dotfiles/$file $HOME/.$file
    echo "[INFO] $file symlinked."
  fi
done

for directory in ${DOT_DIRECTORIES[@]}
do
  if [ -d $HOME/.$directory ]; then
    echo "[WARN] .$directory directory is existed."
  else
    ln -s $HOME/dotfiles/$directory $HOME/.$directory
    echo "[INFO] $directory symlinked."
  fi
done

#
# symlink diff-highlight
#
if [ -L /usr/bin/diff-highlight ]; then
  echo "[WARN] Symlinked diff-highlight"
else
  find /opt/boxen -name diff-highlight | awk 'NR == 2 {print "sudo ln -s",$0,"/usr/local/bin/"}'
  echo "[INFO] diff-highlight symlinked."
fi

#
# ghq
#
if [ -d $HOME/src/github.com/motemen ]; then
  echo "[WARN] Exist ghq"
else
  go get github.com/motemen/ghq
  echo "[INFO] install ghq."
fi

#
# xcode 6
#
XCODE_HOME=${HOME}/Library/Developer/Xcode/UserData/FontAndColorThemes
if [ -L ${XCODE_HOME}/Solarized\ -\ Ae06710.dvtcolortheme ]; then
  echo "[WARN] Exist xcode themes"
else
  echo "[INFO] Copy xcode themes"
  mkdir -p ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
  ln -s ${HOME}/dotfiles/themes/apple-xcode4-solarized/Solarized\ -\ Ae06710.dvtcolortheme ${XCODE_HOME}
fi

#
# sublime_text_3
#
SUBLIME_HOME="${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
SUBLIME_PREFERENCE_FILE="${SUBLIME_HOME}/Preferences.sublime-settings"
if [ -e "${SUBLIME_PREFERENCE_FILE}" ]; then
  echo "[WARN] already exists preference"
else
  echo "[INFO] Symlink Sublime_text preferences"
  ln -s ${HOME}/dotfiles/sublime_text_3/Preferences.sublime-settings "${SUBLIME_HOME}/"
fi

#
# Python
#
packages=(percol awscli)

for package in ${packages[@]}
do
  pip list | grep $package
  if [ $? -eq 0 ]; then
    echo "[WARN] $package is already installed"
  else
    pip install $package
    echo "[INFO] install $package"
  fi
done

#
# mysql setting
#
# $ unset TMPDIR
# $ mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp
#
mysql.server status | grep ERROR
if [ $? -eq 1 ]; then
  echo "[WARN] Started mysql server"
else
  mysql.server start
  echo "[INFO] starting mysql"
fi

#
# memcached
#
if [ -e ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist ]; then
  echo "[WARN] Already symlinked memcached plist"
else
  echo "[INFO] Symlink memcached plist to launchAgent"
  ln -sfv /opt/boxen/homebrew/opt/memcached/*.plist ~/Library/LaunchAgents
fi


# # install via antigen and neobundle
# if [ -a $HOME/.vimrc ]; then
#   source ~/.zshrc
#   vim ~/.vimrc
# fi

# # antigen plugin install
# if [ -d $HOME/zsh/antigen ]; then
#   antigen update
# fi
