#!/bin/bash

# fotns
if [ ! -d $HOME/Dropbox/dev/fonts ]; then
  echo "[ERROR] Fonts directory is not exist"
elif [ -f $HOME/Library/Fonts/Source\ Code\ Pro\ Regular\ for\ Powerline.otf ]; then
  echo "[INFO] Already copied fonts"
else
  echo "Copying fonts to local"
  cp $HOME/Dropbox/dev/fonts/* $HOME/Library/Fonts/
fi

# git
if [ ! -f $HOME/Dropbox/dev/.gitconfig.local ]; then
  echo "[ERROR] .gitconfig.local is not exist in $HOME/Dropbox/dev"
elif [ -f $HOME/.gitconfig.local ]; then
  echo "[INFO] already simlinked .gitconfig.local"
else
  ln -s $HOME/Dropbox/dev/.gitconfig.local $HOME/
  echo "Copying .gitconfig.local to local"
fi

# tmuxinator
if [ ! -d $HOME/Dropbox/dev/tmuxinator ]; then
  echo "[ERROR] tmuxinator setting directory is not exist"
elif [ -L $HOME/.tmuxinator ]; then
  echo "[INFO] Symlinked tmuxinator"
else
  echo "Symlink tmuxinator"
  ln -s $HOME/Dropbox/dev/tmuxinator $HOME/.tmuxinator
fi

# keys
if [ -e $HOME/.ssh/id_rsa ]; then
  echo "[INFO] Exit id_rsa"
  # TODO copy id_rsa file
fi

# Another keys
if [ -L $HOME/.zsh.env ]; then
  echo "[INFO] Exit zsh.env"
else
  echo "Symlink zsh.env"
  ln -s $HOME/Dropbox/dev/zsh.env $HOME/.zsh.env
fi

# papertrail-cli
if [ -L $HOME/.papertrail.yml ]; then
  echo "[INFO] Already exist papertrail.yml"
else
  echo "Symlink papertrail.yml"
  ln -s $HOME/Dropbox/dev/dotfiles/papertrail.yml $HOME/.papertrail.yml
fi
