#!/bin/sh

$HOMEBREW_ROOT/bin/ctags -R \
--exclude=node_modules \
--exclude=spec \
--exclude=public \
--exclude=log \
--exclude=tmp \
--exclude=*.mp4 \
--exclude=*.webm \
--exclude=*.jpg \
--exclude=*.jpeg \
--exclude=*.png \
--exclude=*.gif \
--exclude=*.ico \
--exclude=*.svg \
--exclude=*.slim \
--exclude=*.haml \
--exclude=*.scss \
--exclude=*.sass \
--exclude=*.css \
--exclude=*.js \
--exclude=*.coffee \
-f .git/tags \
`pwd`
