[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  " file
  nnoremap <C-u><C-u> :Denite file/rec<CR>
  " current file and dir
  nnoremap <C-u><C-d> :Denite file<CR>
  " file buffer list
  nnoremap <C-u><C-b> :Denite buffer<CR>

  " grep
  nnoremap <silent>/ :Denite -buffer-name=search -auto-highlight line<CR>
  nnoremap  :Denite -buffer-name=search -auto-highlight line<CR>
  " word grep
  nnoremap <silent>* :DeniteCursorWord -buffer-name=search -auto-highlight -mode=normal line<CR>
  " Change file type
  nnoremap <silent>ft :<C-u>Denite filetype<CR>

  " Denite -buffer-name=search -no-empty -mode=normal grep
  " tab pager
  nnoremap <C-u><C-t> :Denite -select=`tabpagenr()-1` -mode=normal deol<CR>
'''

hook_post_source = '''
  " File search ignore settings
  let ignore_sources = ['.git', '*.png', '*.jpg', '*.jpeg', '*.svg', '*.ico', '*.mp4', '*.webm']

  for ignore_setting_file in ['./.gitignore', expand('~/.config/git/ignore')]
    if filereadable(ignore_setting_file)
      for file in readfile(ignore_setting_file)
        " Skip comment and blank line
        if file !~ "^#\\|^\s\*$"
          call add(ignore_sources, file)
        endif
      endfor
    endif
  endfor

  " " for ignore_source debugging
  " echomsg string(join(ignore_sources, ','))

  call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', ignore_sources)

  if executable('ag')
    " use ag on file/rec
    call denite#custom#var('file/rec', 'command', [ 'ag', '--follow', '--nocolor', '--nogroup', '-g', '' ])

    " Ag command on grep source
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif

  call denite#custom#map(
        \ 'insert',
        \ '<C-j>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
  call denite#custom#map(
        \ 'insert',
        \ '<C-k>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = ['Shougo/unite.vim']
hook_add = '''
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_safe_mode_by_default = 0

  noremap <C-U><C-F> :VimFilerExplorer<CR>

  " " atometic open Vimfilerexplorer
  " let file_name = expand("%")
  " if has('vim_starting') && file_name == ""
  "   autocmd VimEnter * VimFilerExplorer ./
  " endif
'''

# [[plugins]]
# repo = 'tsukkee/unite-tag'
# depends = ['Shougo/unite.vim']
# hook_add = '''
# " If you want to unite-tag instead of |<C-]>|, try to write below in your vimrc.
# autocmd BufEnter *
# \   if empty(&buftype)
# \|      nnoremap <buffer> <C-]> :<C-u>UniteWithCursorWord -immediately tag<CR>
# \|  endif
# " Use Unite jump insted of |<C-t>| back ctag's
# autocmd BufEnter *
# \   if empty(&buftype)
# \|      nnoremap <buffer> <C-t> :<C-u>Unite jump<CR>
# \|  endif
# '''
