#!/bin/bash

# ec2-ip
#
# get ec2's ip
#
function ec2-public-ip() {
    usage_exit() {
        echo "Usage: [-q query] [-c credential]" 1>&2
        return 0
    }

    QUERY=""
    EC2_PROFILE="default"

    while getopts q:c:h OPT
    do
        case $OPT in
            q)  QUERY=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    if [[ $QUERY == "" ]]; then
      PERCOL=percol
    else
      PERCOL="percol --query $QUERY"
    fi

    ec2-instances -c $EC2_PROFILE | eval $PERCOL | awk '{ print $1 }'
}

function ec2-private-ip() {
    usage_exit() {
        echo "Usage: [-q query] [-c credential]" 1>&2
        return 0
    }

    QUERY=""
    EC2_PROFILE="default"

    while getopts q:c:h OPT
    do
        case $OPT in
            q)  QUERY=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    if [[ $QUERY == "" ]]; then
      PERCOL=percol
    else
      PERCOL="percol --query $QUERY"
    fi

    ec2-instances -c $EC2_PROFILE | eval $PERCOL | awk '{ print $2 }'
}

function ec2-instances() {
    usage_exit() {
        echo "Usage: [-c credential]" 1>&2
        return 0
    }

    EC2_PROFILE="default"

    while getopts c:h OPT
    do
        case $OPT in
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    instances=( $(aws ec2 describe-instances \
      --filters 'Name=instance-state-name,Values=running' \
      --query 'Reservations[*].Instances[*].[Tags[?Key==`Name`].Value[],PublicIpAddress,PrivateIpAddress]' \
      --output text \
      --profile $EC2_PROFILE) )

    for i in `seq 1 ${#instances[@]}`; do
      if [ `expr $i % 3` -eq 0 ]; then
        echo ${instances[$i-2]} ${instances[$i-1]} ${instances[$i]}
      fi
    done
}

# ec2-scp
#
# ssh login to ec2 server
#
function ec2-scp() {
    usage_exit() {
        echo "Usage: -u user -p port [-q query] -f original file -o output [-c credential]" 1>&2
        return 0
    }

    QUERY=""
    EC2_SSH_USER=akiramiki
    port=2222
    EC2_PROFILE="default"

    while getopts u:q:i:f:o:p:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            f)  file=$OPTARG
                ;;
            o)  output=$OPTARG
                ;;
            p)  port=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

  if [[ $bucket == "" ]]; then usage_exit; return 0; fi
  if [[ $key == "" ]]; then usage_exit; return 0; fi

  scp -P$port -i ~/.ssh/id_rsa $EC2_SSH_USER@$(ec2-public-ip -q $QUERY -c $EC2_PROFILE):$file $output
}

# ec2-ssh
#
# ssh login to ec2 server
#
function ec2-ssh() {
    usage_exit() {
        echo "Usage: [-u user] [-q query] [-k key] [-c credential]" 1>&2
        return 0
    }

    QUERY=""
    KEY=~/.ssh/id_rsa
    EC2_SSH_USER=akiramiki
    RUN_FLG=1
    EC2_PROFILE="default"

    while getopts u:q:k:c:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            k)  KEY=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    if [[ $RUN_FLG != 0 ]]; then
      ssh $EC2_SSH_USER@$(ec2-public-ip -q $QUERY -c $EC2_PROFILE) -p2222 -i $KEY
    fi
}

# ec2-mosh
#
# ssh login to ec2 server
#
function ec2-mosh() {
    usage_exit() {
        echo "Usage: [-u user] [-q query] [-k key] [-c credential]" 1>&2
        return 0
    }

    QUERY=""
    KEY=~/.ssh/id_rsa
    EC2_SSH_USER=akiramiki
    RUN_FLG=1
    EC2_PROFILE="default"

    while getopts u:q:k:c:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            k)  KEY=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    if [[ $RUN_FLG != 0 ]]; then
      mosh $EC2_SSH_USER@$(ec2-public-ip -q $QUERY -c $EC2_PROFILE) --ssh="ssh -p 2222 -i $KEY"
    fi
}

# ec2-cluster
#
# ssh login to ec2 servers
# required tmux-cssh
#
function ec2-cluster() {
    usage_exit() {
        echo "Usage: [-u user] [-q query] [-k key]" 1>&2
        return 0
    }

    QUERY=""
    KEY=~/.ssh/id_rsa
    EC2_SSH_USER=akiramiki
    RUN_FLG=1
    EC2_PROFILE="default"

    while getopts u:q:k:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            k)  KEY=$OPTARG
                ;;
            c)  EC2_PROFILE=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    HOSTS=$(ec2-public-ip -q $QUERY -c $EC2_PROFILE | sed "s/$/:2222/g" | tr "\n", " ")
    if [[ $RUN_FLG != 0 ]]; then
        sh -c "tmux-cssh -u $EC2_SSH_USER -c $KEY -sc $HOSTS -sa -oStrictHostKeyChecking=no"
    fi
}
