#!/bin/bash

# ec2-ip
#
# get ec2's ip
#
function ec2-ip() {
  if [[ $1 == "" ]]; then
    PERCOL=percol
  else
    PERCOL="percol --query $1"
  fi
  instances | eval $PERCOL | awk '{ print $1 }'
}

function instances() {
  instances=( $(aws ec2 describe-instances \
    --query 'Reservations[*].Instances[*].[Tags[?Key==`Name`].Value[],PublicIpAddress,PrivateIpAddress]' \
    --output text) )

  for i in `seq 1 ${#instances[@]}`; do
    if [ `expr $i % 3` -eq 0 ]; then
      echo ${instances[$i-2]} ${instances[$i-1]} ${instances[$i]}
    fi
  done
}

# ec2-scp
#
# ssh login to ec2 server
#
function ec2-scp() {
    usage_exit() {
        echo "Usage: [-u user] [-p port] [-q query] [-f original file] [-o output]" 1>&2
        return 0
    }

    QUERY=""
    EC2_SSH_USER=akiramiki
    port=2222

    while getopts u:q:i:o:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            f)  file=$OPTARG
                ;;
            o)  output=$OPTARG
                ;;
            p)  port=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

  if [[ $bucket == "" ]]; then usage_exit; return 0; fi
  if [[ $key == "" ]]; then usage_exit; return 0; fi

  scp -P$port -i ~/.ssh/id_rsa $EC2_SSH_USER@$(ec2-ip $QUERY):$file $output
}

# ec2-ssh
#
# ssh login to ec2 server
#
function ec2-ssh() {
    usage_exit() {
        echo "Usage: [-u user] [-q query] [-k key]" 1>&2
        return 0
    }

    QUERY=""
    KEY=~/.ssh/id_rsa
    EC2_SSH_USER=akiramiki
    RUN_FLG=1

    while getopts u:q:k:h OPT
    do
        case $OPT in
            u)  EC2_SSH_USER=$OPTARG
                ;;
            q)  QUERY=$OPTARG
                ;;
            k)  KEY=$OPTARG
                ;;
            h)  usage_exit
                return 0
                ;;
            \?) usage_exit
                return 0
                ;;
        esac
    done

    if [[ $RUN_FLG != 0 ]]; then
      mosh $EC2_SSH_USER@$(ec2-ip $QUERY) --ssh="ssh -p 2222 -i $KEY"
    fi
}

