#!/bin/bash

# ppgrep
#
#
function ppgrep() {
  if [[ $1 == "" ]]; then
    PECO=peco
  else
    PECO="peco --query $1"
  fi
  ps aux | eval $PECO | awk '{ print $2 }'
}

# ppkill
#
#
function ppkill() {
  if [[ $1 =~ "^-" ]]; then
    QUERY=""
  else
    QUERY=$1
    [[ $# > 0 ]] && shift
  fi
  ppgrep $QUERY | xargs kill $*
}

