#!/bin/bash

# ppgrep
#
#
function ppgrep() {
  if [[ $1 == "" ]]; then
    PERCOL=percol
  else
    PERCOL="percol --query $1"
  fi
  ps aux | eval $PERCOL | awk '{ print $2 }'
}

# ppkill
#
#
function ppkill() {
  if [[ $1 =~ "^-" ]]; then
    QUERY=""
  else
    QUERY=$1
    [[ $# > 0 ]] && shift
  fi
  ppgrep $QUERY | xargs kill $*
}

