#!/bin/sh

$HOMEBREW_ROOT/bin/ctags -R \
--exclude=node_modules \
--exclude=public \
--exclude=*.slim \
--exclude=*.haml \
--exclude=*.scss \
--exclude=*.sass \
--exclude=*.css \
--exclude=*.js \
--exclude=*.coffee \
-f .git/tags \
`pwd`

